export const facilityTypes = new Map()
  .set( "AIRPORT","Airport" )
  .set( "ARENA", "Arena" )
  .set( "AUTO_REPAIR", "Auto Repair Shop" )
  .set( "BANK", "Bank" )
  .set( "B_AND_B", "B&B" )
  .set( "BREWERY_DISTILLERY_WINERY", "Brewery/Distillery/Winery" )
  .set( "CAMPGROUND", "Campground" )
  .set( "CAR_DEALER", "Car Dealer" )
  .set( "CARWASH", "Carwash" )
  .set( "COLLEGE_CAMPUS", "College Campus" )
  .set( "CONVENIENCE_STORE", "Convenience Store" )
  .set( "CONVENTION_CENTER", "Convention Center" )
  .set( "COOP", "Co-Op" )
  .set( "FACTORY", "Factory" )
  .set( "FED_GOV", "Federal Government" )
  .set( "FIRE_STATION", "Fire Station" )
  .set( "FLEET_GARAGE", "Fleet Garage" )
  .set( "FUEL_RESELLER", "Fuel Reseller" )
  .set( "GROCERY", "Grocery Store" )
  .set( "HARDWARE_STORE", "Hardware Store" )
  .set( "HOSPITAL", "Hospital" )
  .set( "HOTEL", "Hotel" )
  .set( "INN", "Inn" )
  .set( "LIBRARY", "Library" )
  .set( "MIL_BASE", "Military Base" )
  .set( "MOTOR_POOL", "Motor Pool" )
  .set( "MULTI_UNIT_DWELLING", "Multi-Family Housing" )
  .set( "MUNI_GOV", "Municipal Government" )
  .set( "MUSEUM", "Museum" )
  .set( "NATL_PARK", "National Park" )
  .set( "OFFICE_BLDG", "Office Building" )
  .set( "OTHER", "Other" )
  .set( "OTHER_ENTERTAINMENT", "Other Entertainment" )
  .set( "PARK", "Park" )
  .set( "PARKING_GARAGE", "Parking Garage" )
  .set( "PARKING_LOT", "Parking Lot" )
  .set( "PAY_GARAGE", "Pay-Parking Garage" )
  .set( "PAY_LOT", "Pay-Parking Lot" )
  .set( "PHARMACY", "Pharmacy" )
  .set( "PLACE_OF_WORSHIP", "Place of Worship" )
  .set( "PRISON", "Prison" )
  .set( "PUBLIC", "Public" )
  .set( "REC_SPORTS_FACILITY", "Recreational Sports Facility" )
  .set( "REFINERY", "Refinery" )
  .set( "RENTAL_CAR_RETURN", "Rental Car Return" )
  .set( "RESEARCH_FACILITY", "Research Facility/Laboratory" )
  .set( "RESTAURANT", "Restaurant" )
  .set( "REST_STOP", "Rest Stop" )
  .set( "RETAIL", "Retail" )
  .set( "RV_PARK", "RV Park" )
  .set( "SCHOOL", "School" )
  .set( "GAS_STATION", "Service/Gas Station" )
  .set( "SHOPPING_CENTER", "Shopping Center" )
  .set( "SHOPPING_MALL", "Shopping Mall" )
  .set( "STADIUM", "Stadium" )
  .set( "STANDALONE_STATION", "Standalone Station" )
  .set( "STATE_GOV", "State/Provincial Government" )
  .set( "STORAGE", "Storage Facility" )
  .set( "STREET_PARKING", "Street Parking" )
  .set( "TNC", "Transportation Network Company" )
  .set( "TRAVEL_CENTER", "Travel Center" )
  .set( "TRUCK_STOP", "Truck Stop" )
  .set( "UTILITY", "Utility" )
  .set( "WORKPLACE", "Workplace" );
